name = "shippage-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
SITE_URL = "https://shippage.ai"
FEISHU_APP_ID = "cli_a94ab2ad13b8dcd4"
FEISHU_APP_TOKEN = "EmrDwGsAdizWIFkHtLDct0aznMd"
FEISHU_TABLE_WAITLIST = "tbldfQ7JbDWkdkRf"
FEISHU_TABLE_AGENTS = "tblO3ZGzo3qd40gL"
FEISHU_TABLE_PAGES = "tblXWHrxuh9zcw4o"
FEISHU_TABLE_DAILY_COST = "tblWHqm7dfdboONR"
GOOGLE_CLIENT_ID = "977796719274-kcprgk4vfcff34cr86ln9hhiqu6vjg9p.apps.googleusercontent.com"

[[r2_buckets]]
binding = "PAGES_BUCKET"
bucket_name = "shippage-pages"

[[kv_namespaces]]
binding = "META"
id = "dc7aaef6e68e4a5691b064351eb250a3"

[[routes]]
pattern = "shippage.ai/*"
zone_name = "shippage.ai"

[[routes]]
pattern = "shippage.ai"
zone_name = "shippage.ai"

[triggers]
crons = ["0 3 * * *"]
