export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  updatedAt?: string;
  author: string;
  tags: string[];
  readingTime: number;
  html: string;
}

const POST_HOW_TO_PUBLISH_FROM_CLAUDE: BlogPost = {
  slug: 'how-to-publish-html-from-claude',
  title: 'How to publish HTML from Claude, Cursor, or any AI agent',
  description: 'A 2-minute guide to turning HTML generated by Claude Code, Claude Desktop, Cursor, or any AI agent into a public URL — no account, no build step, no config.',
  publishedAt: '2026-04-19',
  author: 'ShipPage',
  tags: ['tutorial', 'claude', 'cursor', 'mcp', 'openclaw'],
  readingTime: 4,
  html: `
<p class="lead">
  If your AI agent generates HTML — reports, dashboards, landing pages, one-pagers — you need a way to turn that HTML into a shareable URL. This post walks through three zero-config ways to publish HTML from Claude, Cursor, or any tool that can make an HTTP request.
</p>

<p><strong>ShipPage is a zero-config HTML publishing service built for AI agents.</strong> One HTTP POST turns any HTML or Markdown into a public URL at <code>shippage.ai/p/{slug}</code>. No signup, no build pipeline, no deploy keys. Free tier: 20 publishes per month.</p>

<h2 id="claude-code">How do I publish HTML from Claude Code?</h2>

<p>Claude Code is the terminal-based coding agent from Anthropic. It supports <em>skills</em> — installable capabilities that Claude can invoke during a conversation. ShipPage ships as a skill.</p>

<p>Install it once:</p>

<pre><code>clawhub install shippage</code></pre>

<p>Then in any Claude Code session, tell Claude what to do:</p>

<blockquote>"Write a one-page summary of this spec as HTML and publish it as a webpage."</blockquote>

<p>Claude generates the HTML, calls the ShipPage skill, and returns a <code>shippage.ai/p/...</code> URL in the response. No API keys. No environment variables. The first publish auto-registers your agent and saves credentials to <code>~/.shippage/credentials.json</code> for subsequent calls.</p>

<h2 id="claude-desktop-cursor">How do I publish from Claude Desktop or Cursor?</h2>

<p>Claude Desktop and Cursor both speak <em>MCP</em> (Model Context Protocol). ShipPage has an MCP server that exposes publishing tools the AI can invoke directly.</p>

<p>Add this to your <code>claude_desktop_config.json</code> (or Cursor's MCP settings):</p>

<pre><code>{
  "mcpServers": {
    "shippage": {
      "command": "npx",
      "args": ["shippage-mcp"]
    }
  }
}</code></pre>

<p>Restart the app. The ShipPage tools — <code>publish_html</code>, <code>publish_markdown</code>, <code>list_pages</code>, <code>delete_page</code> — become available in every conversation. Ask the model:</p>

<blockquote>"Turn this Markdown into a styled webpage and give me the URL."</blockquote>

<p>The MCP server handles the HTTP call; the model handles the HTML.</p>

<h2 id="any-http-client">How do I publish from GPT, Gemini, or a custom script?</h2>

<p>The ShipPage API is a standard REST endpoint. Anything that can POST JSON can publish:</p>

<pre><code>curl -X POST https://shippage.ai/v1/publish \\
  -H "Content-Type: application/json" \\
  -d '{
    "html": "&lt;html&gt;&lt;body&gt;&lt;h1&gt;Hello&lt;/h1&gt;&lt;/body&gt;&lt;/html&gt;",
    "title": "My page",
    "public": true
  }'</code></pre>

<p>Response:</p>

<pre><code>{
  "ok": true,
  "url": "https://shippage.ai/p/x7k2m9",
  "slug": "x7k2m9",
  "expires_at": "2026-05-03T14:30:00Z",
  "_registration": {
    "api_key": "sk_...",
    "claim_url": "https://shippage.ai/claim/ABCD-1234"
  }
}</code></pre>

<p>Save <code>api_key</code> and pass it as <code>Authorization: Bearer sk_...</code> on subsequent calls. If you want the page to appear in Google search results and <code>shippage.ai/sitemap.xml</code>, pass <code>"public": true</code> in the body.</p>

<h2 id="why-not-vercel">Why not just use Vercel, Netlify, or GitHub Pages?</h2>

<p>Those are excellent for hosting applications with git repos, build pipelines, and deployment configs. They are not built for one-shot AI output delivery. Consider what an AI agent actually needs:</p>

<ul>
  <li><strong>Zero setup per publish.</strong> An agent shouldn't need a git commit, a CI run, and a webhook to publish a report.</li>
  <li><strong>No human in the loop.</strong> No account creation, no email verification, no OAuth consent.</li>
  <li><strong>Ephemeral by default.</strong> Most agent-generated pages should expire. Persistence is the exception, not the rule.</li>
</ul>

<p>ShipPage optimizes for exactly this shape. Vercel optimizes for a product's entire lifecycle. Different tools, different jobs.</p>

<h2 id="managing-pages">How do I list, update, or delete a page I published?</h2>

<p>Once you have an <code>api_key</code>, the CRUD API is standard:</p>

<pre><code>GET    /v1/pages              # list your pages
PUT    /v1/pages/{slug}       # update HTML, title, password, expiry, public flag
DELETE /v1/pages/{slug}       # delete a page</code></pre>

<p>Or visit <code>shippage.ai/claim/{claim_code}</code> — the <code>claim_url</code> returned on first publish — to manage pages via the web UI with a Google login.</p>

<h2 id="next-steps">Next steps</h2>

<ul>
  <li>Install the skill: <code>clawhub install shippage</code></li>
  <li>Browse real published pages: <a href="/showcase">shippage.ai/showcase</a></li>
  <li>Copy a template to start: <a href="/templates">shippage.ai/templates</a></li>
  <li>Read the API docs: <a href="/">shippage.ai</a></li>
</ul>

<p>ShipPage is MIT-licensed and open source at <a href="https://github.com/jieshu666/ShipPage-Skill" rel="noopener">github.com/jieshu666/ShipPage-Skill</a>.</p>
  `.trim(),
};

const POST_VS_VERCEL: BlogPost = {
  slug: 'shippage-vs-vercel-netlify-pagedrop',
  title: 'ShipPage vs Vercel vs Netlify vs PageDrop: which is right for AI-generated pages?',
  description: 'A practical comparison of ShipPage against Vercel, Netlify, and PageDrop for the specific job of publishing HTML generated by AI agents. Each serves a different need — here is when to pick which.',
  publishedAt: '2026-04-19',
  author: 'ShipPage',
  tags: ['comparison', 'vercel', 'netlify', 'pagedrop', 'hosting'],
  readingTime: 6,
  html: `
<p class="lead">
  If your AI agent just generated an HTML report and you want a URL for it, which hosting service is the right choice? This is a practical guide comparing ShipPage, Vercel, Netlify, and PageDrop across the axes that matter: setup time, persistence, agent ergonomics, and cost.
</p>

<h2 id="tldr">TL;DR</h2>

<ul>
  <li><strong>AI agent generating one-shot HTML, no account setup</strong> → ShipPage or PageDrop.</li>
  <li><strong>Need page management (edit, delete, password protect)</strong> → ShipPage.</li>
  <li><strong>Running a full app with a git repo and CI</strong> → Vercel or Netlify.</li>
  <li><strong>Permanent hosting with custom domains and CDN analytics</strong> → Vercel or Netlify (or ShipPage Pro when it launches).</li>
</ul>

<h2 id="feature-matrix">Feature matrix</h2>

<div class="table-wrap">
<table>
  <thead>
    <tr><th>Feature</th><th>ShipPage</th><th>PageDrop</th><th>Vercel</th><th>Netlify</th></tr>
  </thead>
  <tbody>
    <tr><td>Zero-config publish</td><td>✅</td><td>✅</td><td>❌</td><td>❌</td></tr>
    <tr><td>No account to start</td><td>✅ (auto-register)</td><td>✅ (anonymous)</td><td>❌</td><td>❌</td></tr>
    <tr><td>Single HTTP POST to publish</td><td>✅</td><td>✅</td><td>❌ (needs CLI / git push)</td><td>❌</td></tr>
    <tr><td>Agent identity &amp; API key</td><td>✅</td><td>❌</td><td>✅</td><td>✅</td></tr>
    <tr><td>Full CRUD (list/update/delete)</td><td>✅</td><td>❌</td><td>✅</td><td>✅</td></tr>
    <tr><td>Password-protected pages</td><td>✅</td><td>❌</td><td>Paid tier</td><td>Paid tier</td></tr>
    <tr><td>Custom URL slugs</td><td>✅</td><td>❌</td><td>✅</td><td>✅</td></tr>
    <tr><td>MCP server / Skill support</td><td>✅</td><td>❌</td><td>❌</td><td>❌</td></tr>
    <tr><td>Markdown → styled webpage</td><td>✅</td><td>❌</td><td>❌ (needs build)</td><td>❌ (needs build)</td></tr>
    <tr><td>Built-in expiry</td><td>✅ (14 days free)</td><td>✅</td><td>❌</td><td>❌</td></tr>
    <tr><td>Custom domain</td><td>Pro (coming)</td><td>❌</td><td>✅</td><td>✅</td></tr>
    <tr><td>Free tier</td><td>20/month</td><td>Unlimited, anon</td><td>Hobby tier</td><td>Starter tier</td></tr>
  </tbody>
</table>
</div>

<h2 id="shippage">When to pick ShipPage</h2>

<p>Pick ShipPage when your workflow looks like: <em>"AI agent generates HTML. I want a URL."</em> You care about agent ergonomics — zero setup, programmatic CRUD, MCP/Skill integration — more than about custom domains or a build pipeline.</p>

<p>Specific signals:</p>
<ul>
  <li>You use Claude Code, Claude Desktop, or Cursor and want the AI to publish directly.</li>
  <li>You need to password-protect a page your agent generated.</li>
  <li>You want to list and manage all pages a particular agent has published.</li>
  <li>You want Markdown in → styled HTML out, without maintaining a static-site generator.</li>
</ul>

<h2 id="pagedrop">When to pick PageDrop</h2>

<p>PageDrop is the simplest possible HTML hosting. One POST, one URL, no account, no management. Pick it when your publish-and-forget need is even simpler than ShipPage's, and you do not need to edit or delete the page afterward.</p>

<p>Specific signals:</p>
<ul>
  <li>You are publishing anonymously and do not need to link pages to an agent identity.</li>
  <li>You will never need to update, password-protect, or programmatically delete the page.</li>
  <li>The page is genuinely disposable after the first view.</li>
</ul>

<h2 id="vercel">When to pick Vercel</h2>

<p>Vercel is purpose-built for modern frontend apps — Next.js, static sites, serverless functions — with a full deployment lifecycle: git-based deploys, previews, environment variables, custom domains, and team collaboration. Pick Vercel when you are shipping a product, not one-shot output.</p>

<p>Specific signals:</p>
<ul>
  <li>You have a codebase in a git repository.</li>
  <li>You need preview deployments per branch or pull request.</li>
  <li>You want CDN caching, edge middleware, serverless functions.</li>
  <li>You are building a long-lived application, not publishing ephemeral artifacts.</li>
</ul>

<h2 id="netlify">When to pick Netlify</h2>

<p>Netlify plays in the same league as Vercel with strong form handling, identity, and edge functions. The selection criteria overlap heavily — team preference and specific platform features matter more than category differences. Pick either Vercel or Netlify when you are building a site or app, not when you are shipping AI output.</p>

<h2 id="common-misconception">A common misconception</h2>

<p>"Why not just use Vercel's CLI to deploy?" You can — but the agent workflow is awkward. Vercel assumes a project: a directory, a build command, a framework. Your AI-generated one-off HTML has none of that. You would spend more effort wrangling <code>vercel.json</code> than writing the HTML.</p>

<p>ShipPage and PageDrop exist precisely because <em>a single HTML string</em> is the unit AI agents produce — and the right tool should accept exactly that unit with exactly one call.</p>

<h2 id="decision-tree">Decision tree</h2>

<pre><code>Are you publishing a one-off HTML string from an AI agent?
├── Yes → Do you need to edit/delete/password-protect it later?
│        ├── Yes → ShipPage
│        └── No  → PageDrop (or ShipPage if you're on Claude/Cursor)
└── No  → Are you deploying a codebase with git?
         ├── Yes → Vercel or Netlify
         └── No  → rethink the question</code></pre>

<h2 id="start">Getting started with ShipPage</h2>

<p>Install the OpenClaw skill:</p>

<pre><code>clawhub install shippage</code></pre>

<p>Or add the MCP server to Claude Desktop or Cursor:</p>

<pre><code>{"mcpServers":{"shippage":{"command":"npx","args":["shippage-mcp"]}}}</code></pre>

<p>Or just curl the API directly:</p>

<pre><code>curl -X POST https://shippage.ai/v1/publish \\
  -H "Content-Type: application/json" \\
  -d '{"html":"&lt;h1&gt;Hello&lt;/h1&gt;","public":true}'</code></pre>

<p>See the full guide: <a href="/blog/how-to-publish-html-from-claude">How to publish HTML from Claude, Cursor, or any AI agent</a>.</p>
  `.trim(),
};

export const posts: BlogPost[] = [POST_HOW_TO_PUBLISH_FROM_CLAUDE, POST_VS_VERCEL];

export function findPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}
